# kate: indent-width 2;

version: '{branch}-{build}'

branches:
  only:
  - master
  - appveyor-freetype
skip_tags: true
shallow_clone: true
clone_depth: 1

os: Visual Studio 2015

environment:
  matrix:
  - BUILD_STATIC: OFF

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/415ae90928ba0dbd3df4
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

install:
- call "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/vcvarsall.bat"
- set PATH=C:/Sys/bin;C:/tools/ninja;%APPVEYOR_BUILD_FOLDER%/openal/bin/Win32;%PATH%

# Ninja
- cinst ninja

# OpenAL
- appveyor DownloadFile http://kcat.strangesoft.net/openal-soft-1.16.0-bin.zip
- 7z x openal-soft-1.16.0-bin.zip
- ren openal-soft-1.16.0-bin openal
- ren openal\bin\Win32\soft_oal.dll OpenAL32.dll

# LibJPEG Turbo
- appveyor DownloadFile http://downloads.sourceforge.net/project/libjpeg-turbo/1.2.0/libjpeg-turbo-1.2.0.tar.gz
- 7z x libjpeg-turbo-1.2.0.tar.gz
- 7z x libjpeg-turbo-1.2.0.tar
- ren libjpeg-turbo-1.2.0 libjpeg-turbo
- cd libjpeg-turbo
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:/Sys -DWITH_JPEG8=ON -DWITH_SIMD=OFF -G Ninja
- cmake --build .
- cmake --build . --target install
- cd ..
- cd ..

# FreeType
- appveyor DownloadFile http://download.savannah.gnu.org/releases/freetype/freetype-2.6.1.tar.bz2
- 7z x freetype-2.6.1.tar.bz2
- 7z x freetype-2.6.1.tar
- ren freetype-2.6.1 freetype
- cd freetype\builds\windows\vc2010
- msbuild /m /p:Configuration=Release freetype.sln
- cd %APPVEYOR_BUILD_FOLDER%

# Corrade
- git clone --depth 1 git://github.com/mosra/corrade.git
- cd corrade
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:/Sys -DBUILD_STATIC=%BUILD_STATIC% -G Ninja
- cmake --build .
- cmake --build . --target install
- cd ..
- cd ..

# Magnum
- git clone --depth 1 git://github.com/mosra/magnum.git
- cd magnum
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:/Sys -DCMAKE_PREFIX_PATH=%APPVEYOR_BUILD_FOLDER%/openal -DWITH_AUDIO=ON -DWITH_DEBUGTOOLS=OFF -DWITH_PRIMITIVES=OFF -DWITH_SCENEGRAPH=OFF -DWITH_SHADERS=OFF -DWITH_SHAPES=OFF -DWITH_TEXT=ON -DWITH_TEXTURETOOLS=ON -DBUILD_STATIC=%BUILD_STATIC% -G Ninja
- cmake --build .
- cmake --build . --target install
- cd ..
- cd ..

build_script:
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:/Sys -DCMAKE_PREFIX_PATH="%APPVEYOR_BUILD_FOLDER%/openal;%APPVEYOR_BUILD_FOLDER%/freetype" -DFREETYPE_LIBRARY=%APPVEYOR_BUILD_FOLDER%/freetype/objs/vc2010/Win32/freetype261.lib -DWITH_ANYAUDIOIMPORTER=ON -DWITH_ANYIMAGECONVERTER=ON -DWITH_ANYIMAGEIMPORTER=ON -DWITH_ANYSCENEIMPORTER=ON -DWITH_DDSIMPORTER=ON -DWITH_FREETYPEFONT=ON -DWITH_HARFBUZZFONT=OFF -DWITH_JPEGIMPORTER=ON -DWITH_OPENGEXIMPORTER=ON -DWITH_PNGIMPORTER=OFF -DWITH_STANFORDIMPORTER=ON -DWITH_STBIMAGEIMPORTER=ON -DWITH_STBPNGIMAGECONVERTER=ON -DWITH_STBVORBISAUDIOIMPORTER=ON -DBUILD_TESTS=ON -DBUILD_STATIC=%BUILD_STATIC% -G Ninja
- cmake --build .
- cmake --build . --target install
- cmake . -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%/Deploy -DBUILD_TESTS=OFF
- cmake --build . --target install
- cd ../Deploy
- 7z a ../magnum-plugins.zip *

test_script:
- cd %APPVEYOR_BUILD_FOLDER%/build
- SET fail=0
- ctest --output-on-failure || SET fail=1 & ver > nul
- cd %APPVEYOR_BUILD_FOLDER%
- appveyor PushArtifact magnum-plugins.zip
- exit %fail%
